### ISSUE TITLE
`weserv/images` benchmark commentary

### ISSUE THREAD

**Issue by kleisauke** [mamchyts/benchmark-thumbnails#1]
Hello @mamchyts,

Thanks for this interesting performance comparison. I noticed a few things on the [`weserv/images`](https://github.com/weserv/images) benchmark (disclosure: I'm one of the maintainers of this project):
1. The no cache nginx configuration ([`.docker/weserv-images/imagesweserv.conf`](https://github.com/mamchyts/benchmark-thumbnails/blob/aa7cd44deb138a9a2d52a90d0bb0f524a4e2c16a/.docker/weserv-images/imagesweserv.conf)) is still using the `ngx_http_proxy_module`, which shouldn't be necessary if you don't want to use caching. You could use the [`imagesweserv-no-cache.conf`](https://github.com/weserv/images/blob/6171702646129b3dadbbeb7bfe75e4ac9379b714/ngx_conf/imagesweserv-no-cache.conf) config instead. For example:
    ```Dockerfile
    FROM ghcr.io/weserv/images:5.x

    RUN cp ngx_conf/imagesweserv-no-cache.conf /etc/nginx/imagesweserv.conf
    ```
2. I noticed in the [`docker-compose.yaml`](https://github.com/mamchyts/benchmark-thumbnails/blob/aa7cd44deb138a9a2d52a90d0bb0f524a4e2c16a/docker-compose.yaml) file that libvips' concurrency is limited to 1 for the image services that rely on this library, except for `weserv/images`. You might consider using the [`VIPS_CONCURRENCY`](https://github.com/weserv/images/blob/6171702646129b3dadbbeb7bfe75e4ac9379b714/ngx_conf/nginx.conf#L10-L13) environment variable for the `weserv/images` benchmark.
3. The `&fit=crop` parameter is deprecated, consider using the CSS-inspired `&fit=cover` parameter instead.

On the associated blog post (https://habr.com/ru/post/578282/), I noticed this as cons:

- No protection against URL tampering *(translated)*.
- No S3 *(translated)*.

For protection against URL tampering, you can use the [`imagesweserv-secure-link.conf`](https://github.com/weserv/images/blob/6171702646129b3dadbbeb7bfe75e4ac9379b714/ngx_conf/imagesweserv-secure-link.conf) nginx configuration. See the [`ngx_http_secure_link_module` documentation](http://nginx.org/en/docs/http/ngx_http_secure_link_module.html) for more info.

For Amazon S3 support you could use this nginx configuration:
```nginx
location /s3/ {
    weserv filter;

    # The S3 bucket we use
    proxy_pass http://libvips-packaging.s3.amazonaws.com/;
    proxy_set_header Host libvips-packaging.s3.amazonaws.com;

    # Authorization should not be needed on public buckets
    proxy_set_header Authorization '';

    # Header configuration
    proxy_hide_header x-amz-id-2;
    proxy_hide_header x-amz-request-id;
    proxy_hide_header x-amz-meta-server-side-encryption;
    proxy_hide_header x-amz-server-side-encryption;
    proxy_hide_header Set-Cookie;
    proxy_ignore_headers Set-Cookie;

    # Intercept proxy errors
    proxy_intercept_errors on;

    # Enable the upstream persistent connection
    proxy_http_version 1.1;
    proxy_set_header Connection '';
}
```
```bash
$ curl localhost/s3/zebra.jpg?w=200
```
<sup>(see this SO post for more details: https://stackoverflow.com/a/44749584)</sup>

Last but not least, we also support outputting image metadata as JSON (just like imaginary), see for example:
https://images.weserv.nl/static/lichtenstein.jpg?output=json

**Comment by mamchyts** [comment]
Hi @kleisauke.
At the first, thank you for paying attention to my benchmark.

About your 3 notes:
1 - fixed (https://github.com/mamchyts/benchmark-thumbnails/blob/master/.docker/weserv-images/Dockerfile)
2 - I order new AWS instance with a single core (new results of benchmark will be soon)
3 - fixed (you can check new version of README)


What about **No protection against URL tampering (translated).** and **No S3 (translated).**: we use k8s, and we very happy when all features work *from the box* (we want to configure app just by ENV variables). 

I know about http://nginx.org/en/docs/http/ngx_http_secure_link_module.html (I have a big conversation in private messages about this point after publishing https://habr.com/ru/post/578282/)

What about **S3**: at the moment of R&D we had a requirement - read source images from S3, and save thumbnails also into S3 (but in another bucket). But then we finished tests, we saw that there is no performance difference between reading from S3 or from http/https. And delete this point from requirement.

PS. I did update docker-compose.yaml. And after it - looks like your default setup don't use cache: 
```
  weserv-images-cache:
    image: ghcr.io/weserv/images:5.x
    shm_size: 128M
    ports:
      - 8089:80
    restart: always
```   
I want to update benchmark, but can test your solution with cache.


PPS. Your solution is a great. Better yet, it continues to evolve.

**Comment by kleisauke** [comment]
Great! Our nginx configuration [will only load `imagesweserv.conf`](https://github.com/weserv/images/blob/6171702646129b3dadbbeb7bfe75e4ac9379b714/ngx_conf/nginx.conf#L120), so adding a configuration to `/etc/nginx/imagesweserv-no-cache.conf` has no effect. We encourage users to just swap the `/etc/nginx/imagesweserv.conf` configuration with their own, if needed. We provide 2 custom configurations in the Docker image that can be used:
```bash
$ docker run ghcr.io/weserv/images:5.x ls ngx_conf/
README.md
imagesweserv-no-cache.conf
imagesweserv-secure-link.conf
imagesweserv.conf
nginx.conf
```
These can be used like this:
```Dockerfile
FROM ghcr.io/weserv/images:5.x

RUN cp ngx_conf/imagesweserv-no-cache.conf /etc/nginx/imagesweserv.conf
```

> And after it - looks like your default setup don't use cache:

I think the default setup should work, however the `weserv-images` no cache benchmark needs this patch:
```diff
--- a/.docker/weserv-images/Dockerfile
+++ b/.docker/weserv-images/Dockerfile
@@ -1,3 +1,3 @@
 FROM ghcr.io/weserv/images:5.x
 
-ADD https://raw.githubusercontent.com/weserv/images/5.x/ngx_conf/imagesweserv-no-cache.conf /etc/nginx/imagesweserv-no-cache.conf
+RUN cp ngx_conf/imagesweserv-no-cache.conf /etc/nginx/imagesweserv.conf
```
Note that we send the `X-Cache-Status: HIT` response header when an image is delivered from the cache, which could help debug this further.

**Comment by mamchyts** [comment]
`no cache benchmark` updated.

What about default setup - still not working.
Headers after 5+ request:

```
Access-Control-Allow-Origin: *
Cache-Control: public, max-age=31536000
Connection: keep-alive
Content-Disposition: inline; filename=image.jpg
Content-Length: 45927
Content-Type: image/jpeg
Cross-Origin-Resource-Policy: cross-origin
Date: Tue, 14 Dec 2021 10:14:24 GMT
Expires: Wed, 14 Dec 2022 10:14:23 GMT
Link: <https://raw.githubusercontent.com/mamchyts/benchmark-thumbnails/master/pexels-magda-ehlers.jpg>; rel="canonical"
Server: nginx
Timing-Allow-Origin: *
X-Cache-Status: BYPASS
X-Images-Api: 5
X-Upstream-Response-Length: 1730508
```


Request timeout ~ 1.2 seconds

**Comment by kleisauke** [comment]
> ```
> X-Cache-Status: BYPASS
> ```

The cache is bypassed if the `Pragma: no-cache` or an authorization request header is present. See:
https://github.com/weserv/images/blob/6171702646129b3dadbbeb7bfe75e4ac9379b714/ngx_conf/imagesweserv.conf#L130
```nginx
proxy_cache_bypass $http_pragma $http_authorization;
```

This can happen in the browser if you do <kbd>CTRL</kbd> + <kbd>F5</kbd>. Or when the DevTools window in Google Chrome (or Firefox) is open and the `Disable cache` box is checked.

> Request timeout ~ 1.2 seconds

Oh curious, when I tested the Docker image locally and resized the [`pexels-magda-ehlers.jpg`](https://github.com/mamchyts/benchmark-thumbnails/blob/b3bc53adb69a621d868a4a27b8d15dbd7bed6be6/pexels-magda-ehlers.jpg) image to 1280 x 720 (`&w=1280&h=720&fit=cover`), I get a TTFB around 300ms with caching disabled.

**Comment by mamchyts** [comment]
```
The cache is bypassed if the Pragma: no-cache or an authorization request header is present
```

You are right.
After removing `Pragma: no-cache` - all works fine.
I will update benchmark in near future.

**Comment by kleisauke** [comment]
Great! I think we're done, looking forward to the new benchmark results.

If you have any questions, please feel free to ask.

**Comment by mamchyts** [comment]
Updated

**Comment by kleisauke** [comment]
Results are OK, although the `t2.small` EC2 instance is not very powerful. For example, resizing the [`pexels-magda-ehlers.jpg`](https://github.com/mamchyts/benchmark-thumbnails/blob/2f024635c238c7eda5497afa6a2e5bcfc366cfc8/pexels-magda-ehlers.jpg) image to 3840x2160 can be done within ~230ms on this PC.
```bash
$ /usr/bin/time -f %M:%e ./bin/weserv-cli pexels-magda-ehlers.jpg x.jpg "w=3840&h=2160&fit=cover"
Processing image "pexels-magda-ehlers.jpg" with query arguments "w=3840&h=2160&fit=cover&output=jpg"
132012:0.23
```

I had a look at the reason for the overhead compared to the other libvips-based image services (i.e. `imgproxy` and `imaginary`). It seems that most of the overhead is spent on improving the output (tested on `t2.small`).
```bash
$ sudo docker exec -it weserv bash

# Download test image and install required deps
$ curl -LO https://raw.githubusercontent.com/mamchyts/benchmark-thumbnails/master/pexels-magda-ehlers.jpg
$ dnf install -y time vips-tools

# Sanity check whether weserv-cli and vipsthumbnail uses the same options
$ ./bin/weserv-cli pexels-magda-ehlers.jpg x.jpg
$ vipsthumbnail pexels-magda-ehlers.jpg -s 5141x3434 -i srgb -e srgb -n perceptual -o x2.jpg[Q=80,strip,optimize_coding]
$ ls -lh x*.jpg
-rw-r--r-- 1 root root 1.3M Dec 16 19:24 x.jpg
-rw-r--r-- 1 root root 1.3M Dec 16 19:24 x2.jpg
$ sha256sum x*.jpg
db574f19449fbcb1341ea9b9014f3132fa8b3a0d12d1825adf1add47e46be2d2  x.jpg
db574f19449fbcb1341ea9b9014f3132fa8b3a0d12d1825adf1add47e46be2d2  x2.jpg

# Check ICC profile conversion overhead (~300ms)
$ /usr/bin/time -f %M:%e vips copy pexels-magda-ehlers.jpg x.jpg[Q=80,strip,optimize_coding]
134688:0.46
$ /usr/bin/time -f %M:%e vipsthumbnail pexels-magda-ehlers.jpg -s 5141x3434 -i srgb -e srgb -n perceptual -o x.jpg[Q=80,strip,optimize_coding]
135712:0.76

# Check `optimize_coding` overhead (~110ms)
$ /usr/bin/time -f %M:%e vips copy pexels-magda-ehlers.jpg x.jpg[Q=80,strip]
82900:0.35

# Total overhead spent on improving output = 410ms
```
